// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using api.Lib;

#nullable disable

namespace api.Data.Migrations
{
    [DbContext(typeof(DBContext))]
    [Migration("20260929120427_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("api.Model.Account", b =>
                {
                    b.Property<Guid>("Uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("HospitalUuid")
                        .HasColumnType("uuid");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid?>("RoleUuid")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Uuid");

                    b.HasIndex("HospitalUuid");

                    b.HasIndex("Phone")
                        .IsUnique();

                    b.HasIndex("RoleUuid");

                    b.ToTable("Account");
                });

            modelBuilder.Entity("api.Model.Appointment", b =>
                {
                    b.Property<Guid>("Uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AppointmentDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DoctorNote")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("DoctorUuid")
                        .HasColumnType("uuid");

                    b.Property<int>("Gender")
                        .HasColumnType("integer");

                    b.Property<Guid?>("HospitalUuid")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("boolean");

                    b.Property<string>("MedicalCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("MedicalServiceUuid")
                        .HasColumnType("uuid");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PatientName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("PatientUuid")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("RoomUuid")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid?>("TimeSlot")
                        .HasColumnType("uuid");

                    b.Property<int>("TotalPrice")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Uuid");

                    b.HasIndex("DoctorUuid");

                    b.HasIndex("HospitalUuid");

                    b.HasIndex("MedicalServiceUuid");

                    b.HasIndex("PatientUuid");

                    b.HasIndex("RoomUuid");

                    b.HasIndex("TimeSlot");

                    b.ToTable("Appointment");
                });

            modelBuilder.Entity("api.Model.AppointmentMedicalService", b =>
                {
                    b.Property<Guid>("Uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AppointmentUuid")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("MedicalServiceUuid")
                        .HasColumnType("uuid");

                    b.Property<int>("Price")
                        .HasColumnType("integer");

                    b.HasKey("Uuid");

                    b.HasIndex("AppointmentUuid");

                    b.HasIndex("MedicalServiceUuid");

                    b.ToTable("AppointmentMedicalService");
                });

            modelBuilder.Entity("api.Model.AuditLog", b =>
                {
                    b.Property<Guid>("Uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.HasKey("Uuid");

                    b.ToTable("AuditLog");
                });

            modelBuilder.Entity("api.Model.Department", b =>
                {
                    b.Property<Guid>("Uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Uuid");

                    b.ToTable("Department");
                });

            modelBuilder.Entity("api.Model.DoctorDepartment", b =>
                {
                    b.Property<Guid>("Uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("DepartmentUuid")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("DoctorUuid")
                        .HasColumnType("uuid");

                    b.HasKey("Uuid");

                    b.HasIndex("DepartmentUuid");

                    b.HasIndex("DoctorUuid");

                    b.ToTable("DoctorDepartment");
                });

            modelBuilder.Entity("api.Model.DoctorProfile", b =>
                {
                    b.Property<Guid>("Uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AccountUuid")
                        .HasColumnType("uuid");

                    b.Property<string>("Avatar")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DepartmentDisplay")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Expertise")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("HospitalUuid")
                        .HasColumnType("uuid");

                    b.Property<string>("Introduction")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Price")
                        .HasColumnType("integer");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Specialty")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Workplace")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Uuid");

                    b.HasIndex("AccountUuid")
                        .IsUnique();

                    b.HasIndex("HospitalUuid");

                    b.ToTable("DoctorProfile");
                });

            modelBuilder.Entity("api.Model.DoctorWorking", b =>
                {
                    b.Property<Guid>("Uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("DoctorUuid")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("WorkingUuid")
                        .HasColumnType("uuid");

                    b.HasKey("Uuid");

                    b.HasIndex("DoctorUuid");

                    b.HasIndex("WorkingUuid");

                    b.ToTable("DoctorWorking");
                });

            modelBuilder.Entity("api.Model.ExportTicket", b =>
                {
                    b.Property<Guid>("Uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AccountUuid")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("HospitalUuid")
                        .HasColumnType("uuid");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Uuid");

                    b.HasIndex("AccountUuid");

                    b.HasIndex("HospitalUuid");

                    b.ToTable("ExportTicket");
                });

            modelBuilder.Entity("api.Model.ExportTicketDetail", b =>
                {
                    b.Property<Guid>("Uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ExportTicketUuid")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("MedicineUuid")
                        .HasColumnType("uuid");

                    b.Property<int>("Price")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("Uuid");

                    b.HasIndex("ExportTicketUuid");

                    b.HasIndex("MedicineUuid");

                    b.ToTable("ExportTicketDetail");
                });

            modelBuilder.Entity("api.Model.Hospital", b =>
                {
                    b.Property<Guid>("Uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DetailService")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MapUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("NumberOfRoom")
                        .HasColumnType("integer");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("WorkingHour")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Uuid");

                    b.ToTable("Hospital");
                });

            modelBuilder.Entity("api.Model.HospitalDepartment", b =>
                {
                    b.Property<Guid>("Uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("DepartmentUuid")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("HospitalUuid")
                        .HasColumnType("uuid");

                    b.HasKey("Uuid");

                    b.HasIndex("DepartmentUuid");

                    b.HasIndex("HospitalUuid");

                    b.ToTable("HospitalDepartment");
                });

            modelBuilder.Entity("api.Model.HospitalMedicalService", b =>
                {
                    b.Property<Guid>("Uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("HospitalUuid")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("MedicalServiceUuid")
                        .HasColumnType("uuid");

                    b.HasKey("Uuid");

                    b.HasIndex("HospitalUuid");

                    b.HasIndex("MedicalServiceUuid");

                    b.ToTable("HospitalMedicalService");
                });

            modelBuilder.Entity("api.Model.HospitalWorking", b =>
                {
                    b.Property<Guid>("Uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("HospitalUuid")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("WorkingUuid")
                        .HasColumnType("uuid");

                    b.HasKey("Uuid");

                    b.HasIndex("HospitalUuid");

                    b.HasIndex("WorkingUuid");

                    b.ToTable("HospitalWorking");
                });

            modelBuilder.Entity("api.Model.ImportTicket", b =>
                {
                    b.Property<Guid>("Uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AccountUuid")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("HospitalUuid")
                        .HasColumnType("uuid");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ProviderUuid")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Uuid");

                    b.HasIndex("AccountUuid");

                    b.HasIndex("HospitalUuid");

                    b.HasIndex("ProviderUuid");

                    b.ToTable("ImportTicket");
                });

            modelBuilder.Entity("api.Model.ImportTicketDetail", b =>
                {
                    b.Property<Guid>("Uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ImportTicketUuid")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("MedicineUuid")
                        .HasColumnType("uuid");

                    b.Property<int>("Price")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("Uuid");

                    b.HasIndex("ImportTicketUuid");

                    b.HasIndex("MedicineUuid");

                    b.ToTable("ImportTicketDetail");
                });

            modelBuilder.Entity("api.Model.MedicalService", b =>
                {
                    b.Property<Guid>("Uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DetailService")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("InsuranceCap")
                        .HasColumnType("integer");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsInsured")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Price")
                        .HasColumnType("integer");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("WorkingHour")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Uuid");

                    b.ToTable("MedicalService");
                });

            modelBuilder.Entity("api.Model.Medicine", b =>
                {
                    b.Property<Guid>("Uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<float>("InsuranceCap")
                        .HasColumnType("real");

                    b.Property<bool>("IsInsured")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Price")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("Unit")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Uuid");

                    b.ToTable("Medicine");
                });

            modelBuilder.Entity("api.Model.MedicineInventory", b =>
                {
                    b.Property<Guid>("Uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("HospitalUuid")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("MedicineUuid")
                        .HasColumnType("uuid");

                    b.Property<int>("MinimumQuantity")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Uuid");

                    b.HasIndex("HospitalUuid");

                    b.HasIndex("MedicineUuid");

                    b.ToTable("MedicineInventory");
                });

            modelBuilder.Entity("api.Model.MomoLog", b =>
                {
                    b.Property<Guid>("Uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.HasKey("Uuid");

                    b.ToTable("MomoLog");
                });

            modelBuilder.Entity("api.Model.PatientProfile", b =>
                {
                    b.Property<Guid>("Uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AccountUuid")
                        .HasColumnType("uuid");

                    b.Property<string>("Avatar")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Birthdate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)");

                    b.Property<int>("Gender")
                        .HasColumnType("integer");

                    b.Property<string>("MedicalCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Uuid");

                    b.HasIndex("AccountUuid")
                        .IsUnique();

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("PatientProfile");
                });

            modelBuilder.Entity("api.Model.Permission", b =>
                {
                    b.Property<Guid>("Uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Uuid");

                    b.ToTable("Permission");

                    b.HasData(
                        new
                        {
                            Uuid = new Guid("00000000-0000-0000-0000-000000000001"),
                            Description = "Theo dõi tình trạng vận hành và dữ liệu tổng hợp toàn hệ thống.",
                            Icon = "dashboard",
                            Name = "tong-quan-he-thong"
                        },
                        new
                        {
                            Uuid = new Guid("00000000-0000-0000-0000-000000000002"),
                            Description = "Quản lý chi nhánh và trạng thái hoạt động trên toàn hệ thống.",
                            Icon = "hospital",
                            Name = "co-so-y-te"
                        },
                        new
                        {
                            Uuid = new Guid("00000000-0000-0000-0000-000000000003"),
                            Description = "Quản lý danh mục chuyên khoa gốc dùng chung.",
                            Icon = "department",
                            Name = "chuyen-khoa"
                        },
                        new
                        {
                            Uuid = new Guid("00000000-0000-0000-0000-000000000004"),
                            Description = "Quản lý danh mục dịch vụ y tế gốc dùng chung.",
                            Icon = "service",
                            Name = "dich-vu"
                        },
                        new
                        {
                            Uuid = new Guid("00000000-0000-0000-0000-000000000005"),
                            Description = "Quản lý danh mục thuốc dùng chung giữa các chi nhánh.",
                            Icon = "medicine",
                            Name = "thuoc"
                        },
                        new
                        {
                            Uuid = new Guid("00000000-0000-0000-0000-000000000006"),
                            Description = "Quản lý tài khoản và quản trị viên chi nhánh.",
                            Icon = "account",
                            Name = "tai-khoan"
                        },
                        new
                        {
                            Uuid = new Guid("00000000-0000-0000-0000-000000000007"),
                            Description = "Xem báo cáo tổng hợp không bao gồm nội dung lâm sàng chi tiết.",
                            Icon = "report",
                            Name = "bao-cao-he-thong"
                        },
                        new
                        {
                            Uuid = new Guid("00000000-0000-0000-0000-000000000008"),
                            Description = "Theo dõi audit log và các hành động quản trị quan trọng.",
                            Icon = "audit",
                            Name = "nhat-ky-he-thong"
                        },
                        new
                        {
                            Uuid = new Guid("00000000-0000-0000-0000-000000000009"),
                            Description = "Theo dõi hoạt động khám chữa bệnh và vận hành trong chi nhánh.",
                            Icon = "dashboard",
                            Name = "tong-quan-chi-nhanh"
                        },
                        new
                        {
                            Uuid = new Guid("00000000-0000-0000-0000-000000000010"),
                            Description = "Cập nhật thông tin và giờ làm việc của chi nhánh.",
                            Icon = "hospital",
                            Name = "thong-tin-chi-nhanh"
                        },
                        new
                        {
                            Uuid = new Guid("00000000-0000-0000-0000-000000000011"),
                            Description = "Gán chuyên khoa và dịch vụ có sẵn cho chi nhánh.",
                            Icon = "department",
                            Name = "chuyen-khoa-dich-vu"
                        },
                        new
                        {
                            Uuid = new Guid("00000000-0000-0000-0000-000000000012"),
                            Description = "Quản lý phòng và trạng thái sử dụng trong chi nhánh.",
                            Icon = "room",
                            Name = "phong-kham-chi-nhanh"
                        },
                        new
                        {
                            Uuid = new Guid("00000000-0000-0000-0000-000000000013"),
                            Description = "Quản lý tài khoản nhân sự thuộc phạm vi chi nhánh.",
                            Icon = "account",
                            Name = "nhan-su"
                        },
                        new
                        {
                            Uuid = new Guid("00000000-0000-0000-0000-000000000014"),
                            Description = "Theo dõi, xác nhận, điều phối và hủy lịch thuộc chi nhánh.",
                            Icon = "appointment",
                            Name = "lich-hen-chi-nhanh"
                        },
                        new
                        {
                            Uuid = new Guid("00000000-0000-0000-0000-000000000015"),
                            Description = "Xem đơn thuốc khi cần xử lý nghiệp vụ được phân quyền.",
                            Icon = "prescription",
                            Name = "don-thuoc-chi-nhanh"
                        },
                        new
                        {
                            Uuid = new Guid("00000000-0000-0000-0000-000000000016"),
                            Description = "Theo dõi tồn kho và duyệt phiếu nhập xuất của chi nhánh.",
                            Icon = "inventory",
                            Name = "kho-thuoc"
                        },
                        new
                        {
                            Uuid = new Guid("00000000-0000-0000-0000-000000000017"),
                            Description = "Kiểm duyệt đánh giá liên quan đến chi nhánh.",
                            Icon = "review",
                            Name = "danh-gia-chi-nhanh"
                        },
                        new
                        {
                            Uuid = new Guid("00000000-0000-0000-0000-000000000018"),
                            Description = "Xem báo cáo vận hành và tài chính trong phạm vi chi nhánh.",
                            Icon = "report",
                            Name = "bao-cao-chi-nhanh"
                        },
                        new
                        {
                            Uuid = new Guid("00000000-0000-0000-0000-000000000019"),
                            Description = "Theo dõi audit log của chi nhánh.",
                            Icon = "audit",
                            Name = "nhat-ky-chi-nhanh"
                        },
                        new
                        {
                            Uuid = new Guid("00000000-0000-0000-0000-000000000020"),
                            Description = "Theo dõi lịch khám và công việc chuyên môn được phân công.",
                            Icon = "dashboard",
                            Name = "tong-quan-bac-si"
                        },
                        new
                        {
                            Uuid = new Guid("00000000-0000-0000-0000-000000000021"),
                            Description = "Xem lịch khám được phân công và đề xuất thay đổi khi cần.",
                            Icon = "appointment",
                            Name = "lich-kham"
                        },
                        new
                        {
                            Uuid = new Guid("00000000-0000-0000-0000-000000000022"),
                            Description = "Xem thông tin tối thiểu của bệnh nhân và hoàn thành ca khám.",
                            Icon = "patient",
                            Name = "ca-kham"
                        },
                        new
                        {
                            Uuid = new Guid("00000000-0000-0000-0000-000000000023"),
                            Description = "Tạo và quản lý đơn thuốc chưa thanh toán.",
                            Icon = "prescription",
                            Name = "don-thuoc-bac-si"
                        },
                        new
                        {
                            Uuid = new Guid("00000000-0000-0000-0000-000000000024"),
                            Description = "Tra cứu khả dụng của thuốc tại chi nhánh để hỗ trợ kê đơn.",
                            Icon = "medicine",
                            Name = "thuoc-kha-dung"
                        },
                        new
                        {
                            Uuid = new Guid("00000000-0000-0000-0000-000000000025"),
                            Description = "Cập nhật phần thông tin nghề nghiệp được cho phép.",
                            Icon = "profile",
                            Name = "ho-so-nghe-nghiep"
                        },
                        new
                        {
                            Uuid = new Guid("00000000-0000-0000-0000-000000000026"),
                            Description = "Theo dõi lịch hẹn, lượt chờ và tình trạng phòng trong ngày.",
                            Icon = "dashboard",
                            Name = "tong-quan-tiep-nhan"
                        },
                        new
                        {
                            Uuid = new Guid("00000000-0000-0000-0000-000000000027"),
                            Description = "Tạo lịch thay bệnh nhân, xác nhận, đổi lịch và phân phòng.",
                            Icon = "appointment",
                            Name = "lich-hen-tiep-nhan"
                        },
                        new
                        {
                            Uuid = new Guid("00000000-0000-0000-0000-000000000028"),
                            Description = "Check-in và cập nhật trạng thái vận hành của lượt khám.",
                            Icon = "patient",
                            Name = "tiep-nhan"
                        },
                        new
                        {
                            Uuid = new Guid("00000000-0000-0000-0000-000000000029"),
                            Description = "Theo dõi và cập nhật trạng thái phòng trong chi nhánh.",
                            Icon = "room",
                            Name = "phong-kham-tiep-nhan"
                        },
                        new
                        {
                            Uuid = new Guid("00000000-0000-0000-0000-000000000030"),
                            Description = "Thu tiền và cấp thuốc theo đơn khi được giao nhiệm vụ.",
                            Icon = "payment",
                            Name = "thanh-toan-cap-thuoc"
                        },
                        new
                        {
                            Uuid = new Guid("00000000-0000-0000-0000-000000000031"),
                            Description = "Hỗ trợ kiểm duyệt đánh giá khi có quyền phù hợp.",
                            Icon = "review",
                            Name = "danh-gia-tiep-nhan"
                        },
                        new
                        {
                            Uuid = new Guid("00000000-0000-0000-0000-000000000032"),
                            Description = "Theo dõi tồn kho, cảnh báo và hoạt động nhập xuất gần đây.",
                            Icon = "dashboard",
                            Name = "tong-quan-kho"
                        },
                        new
                        {
                            Uuid = new Guid("00000000-0000-0000-0000-000000000033"),
                            Description = "Xem số lượng thuốc hiện có trong kho chi nhánh.",
                            Icon = "inventory",
                            Name = "ton-kho"
                        },
                        new
                        {
                            Uuid = new Guid("00000000-0000-0000-0000-000000000035"),
                            Description = "Quản lý thông tin nhà cung cấp trong phạm vi được giao.",
                            Icon = "provider",
                            Name = "nha-cung-cap"
                        },
                        new
                        {
                            Uuid = new Guid("00000000-0000-0000-0000-000000000036"),
                            Description = "Tạo, sửa hoặc hủy phiếu khi còn chờ duyệt.",
                            Icon = "ticket",
                            Name = "phieu-nhap-xuat"
                        },
                        new
                        {
                            Uuid = new Guid("00000000-0000-0000-0000-000000000037"),
                            Description = "Điều chỉnh tồn kho với lý do bắt buộc và audit log.",
                            Icon = "medicine",
                            Name = "dieu-chinh-ton"
                        },
                        new
                        {
                            Uuid = new Guid("00000000-0000-0000-0000-000000000038"),
                            Description = "Tra cứu lịch sử nhập, xuất và biến động tồn kho.",
                            Icon = "history",
                            Name = "lich-su"
                        },
                        new
                        {
                            Uuid = new Guid("00000000-0000-0000-0000-000000000039"),
                            Description = "Xem báo cáo nhập, xuất, tồn và giá trị kho của chi nhánh.",
                            Icon = "report",
                            Name = "bao-cao-kho"
                        },
                        new
                        {
                            Uuid = new Guid("00000000-0000-0000-0000-000000000040"),
                            Description = "Quản lý danh mục khung giờ dùng chung trong hệ thống.",
                            Icon = "schedule",
                            Name = "khung-gio-lam-viec"
                        },
                        new
                        {
                            Uuid = new Guid("00000000-0000-0000-0000-000000000041"),
                            Description = "Gán và cập nhật lịch thực hiện cho dịch vụ.",
                            Icon = "schedule",
                            Name = "gio-lam-viec-dich-vu"
                        },
                        new
                        {
                            Uuid = new Guid("00000000-0000-0000-0000-000000000042"),
                            Description = "Quản lý role và permission của cổng nội bộ.",
                            Icon = "permission",
                            Name = "phan-quyen"
                        },
                        new
                        {
                            Uuid = new Guid("00000000-0000-0000-0000-000000000043"),
                            Description = "Cập nhật lịch hoạt động của bệnh viện.",
                            Icon = "schedule",
                            Name = "gio-lam-viec-benh-vien"
                        },
                        new
                        {
                            Uuid = new Guid("00000000-0000-0000-0000-000000000044"),
                            Description = "Xem lịch làm việc và tạo đơn đề nghị thay đổi.",
                            Icon = "schedule",
                            Name = "gio-lam-viec-bac-si"
                        });
                });

            modelBuilder.Entity("api.Model.Prescription", b =>
                {
                    b.Property<Guid>("Uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AppointmentUuid")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DoctorProfileUuid")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("HospitalUuid")
                        .HasColumnType("uuid");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("PatientProfileUuid")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Uuid");

                    b.HasIndex("AppointmentUuid");

                    b.HasIndex("DoctorProfileUuid");

                    b.HasIndex("HospitalUuid");

                    b.HasIndex("PatientProfileUuid");

                    b.ToTable("Prescription");
                });

            modelBuilder.Entity("api.Model.PrescriptionDetail", b =>
                {
                    b.Property<Guid>("Uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("DosesPerDay")
                        .HasColumnType("integer");

                    b.Property<int>("Duration")
                        .HasColumnType("integer");

                    b.Property<bool>("IsExternal")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("MedicineUuid")
                        .HasColumnType("uuid");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("PrescriptionUuid")
                        .HasColumnType("uuid");

                    b.Property<int>("Price")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<int>("QuantityPerDose")
                        .HasColumnType("integer");

                    b.HasKey("Uuid");

                    b.HasIndex("MedicineUuid");

                    b.HasIndex("PrescriptionUuid");

                    b.ToTable("PrescriptionDetail");
                });

            modelBuilder.Entity("api.Model.Provider", b =>
                {
                    b.Property<Guid>("Uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Hotline")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Uuid");

                    b.ToTable("Provider");
                });

            modelBuilder.Entity("api.Model.ReviewDoctor", b =>
                {
                    b.Property<Guid>("Uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DoctorUuid")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsViewed")
                        .HasColumnType("boolean");

                    b.Property<int>("NumberOfStar")
                        .HasColumnType("integer");

                    b.Property<Guid?>("PatientUuid")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Uuid");

                    b.HasIndex("DoctorUuid");

                    b.HasIndex("PatientUuid");

                    b.ToTable("ReviewDoctor");
                });

            modelBuilder.Entity("api.Model.ReviewHospital", b =>
                {
                    b.Property<Guid>("Uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("HospitalUuid")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsViewed")
                        .HasColumnType("boolean");

                    b.Property<int>("NumberOfStar")
                        .HasColumnType("integer");

                    b.Property<Guid?>("PatientUuid")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Uuid");

                    b.HasIndex("HospitalUuid");

                    b.HasIndex("PatientUuid");

                    b.ToTable("ReviewHospital");
                });

            modelBuilder.Entity("api.Model.ReviewMedicalService", b =>
                {
                    b.Property<Guid>("Uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsViewed")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("MedicalServiceUuid")
                        .HasColumnType("uuid");

                    b.Property<int>("NumberOfStar")
                        .HasColumnType("integer");

                    b.Property<Guid?>("PatientUuid")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Uuid");

                    b.HasIndex("MedicalServiceUuid");

                    b.HasIndex("PatientUuid");

                    b.ToTable("ReviewMedicalService");
                });

            modelBuilder.Entity("api.Model.Role", b =>
                {
                    b.Property<Guid>("Uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDoctor")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Uuid");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Role");

                    b.HasData(
                        new
                        {
                            Uuid = new Guid("00000000-0000-0000-0000-000000000100"),
                            CreatedAt = new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Tai khoan nguoi benh",
                            IsDoctor = false,
                            Name = "Patient",
                            Status = 0,
                            UpdatedAt = new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("api.Model.RolePermission", b =>
                {
                    b.Property<Guid>("Uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Action")
                        .HasColumnType("integer");

                    b.Property<Guid?>("PermissionUuid")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("RoleUuid")
                        .HasColumnType("uuid");

                    b.HasKey("Uuid");

                    b.HasIndex("PermissionUuid");

                    b.HasIndex("RoleUuid");

                    b.ToTable("RolePermission");
                });

            modelBuilder.Entity("api.Model.Room", b =>
                {
                    b.Property<Guid>("Uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("HospitalUuid")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Uuid");

                    b.HasIndex("HospitalUuid");

                    b.ToTable("Room");
                });

            modelBuilder.Entity("api.Model.ServiceWorking", b =>
                {
                    b.Property<Guid>("Uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ServiceUuid")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("WorkingUuid")
                        .HasColumnType("uuid");

                    b.HasKey("Uuid");

                    b.HasIndex("ServiceUuid");

                    b.HasIndex("WorkingUuid");

                    b.ToTable("ServiceWorking");
                });

            modelBuilder.Entity("api.Model.TimeWorking", b =>
                {
                    b.Property<Guid>("Uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time without time zone");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time without time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Uuid");

                    b.ToTable("TimeWorking");
                });

            modelBuilder.Entity("api.Model.Account", b =>
                {
                    b.HasOne("api.Model.Hospital", null)
                        .WithMany()
                        .HasForeignKey("HospitalUuid")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("api.Model.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleUuid")
                        .OnDelete(DeleteBehavior.NoAction);
                });

            modelBuilder.Entity("api.Model.Appointment", b =>
                {
                    b.HasOne("api.Model.DoctorProfile", null)
                        .WithMany()
                        .HasForeignKey("DoctorUuid")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("api.Model.Hospital", null)
                        .WithMany()
                        .HasForeignKey("HospitalUuid")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("api.Model.MedicalService", null)
                        .WithMany()
                        .HasForeignKey("MedicalServiceUuid")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("api.Model.PatientProfile", null)
                        .WithMany()
                        .HasForeignKey("PatientUuid")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("api.Model.Room", null)
                        .WithMany()
                        .HasForeignKey("RoomUuid")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("api.Model.TimeWorking", null)
                        .WithMany()
                        .HasForeignKey("TimeSlot")
                        .OnDelete(DeleteBehavior.NoAction);
                });

            modelBuilder.Entity("api.Model.AppointmentMedicalService", b =>
                {
                    b.HasOne("api.Model.Appointment", null)
                        .WithMany()
                        .HasForeignKey("AppointmentUuid")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("api.Model.MedicalService", null)
                        .WithMany()
                        .HasForeignKey("MedicalServiceUuid")
                        .OnDelete(DeleteBehavior.NoAction);
                });

            modelBuilder.Entity("api.Model.DoctorDepartment", b =>
                {
                    b.HasOne("api.Model.Department", null)
                        .WithMany()
                        .HasForeignKey("DepartmentUuid")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("api.Model.DoctorProfile", null)
                        .WithMany()
                        .HasForeignKey("DoctorUuid")
                        .OnDelete(DeleteBehavior.NoAction);
                });

            modelBuilder.Entity("api.Model.DoctorProfile", b =>
                {
                    b.HasOne("api.Model.Account", null)
                        .WithOne()
                        .HasForeignKey("api.Model.DoctorProfile", "AccountUuid")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("api.Model.Hospital", null)
                        .WithMany()
                        .HasForeignKey("HospitalUuid")
                        .OnDelete(DeleteBehavior.NoAction);
                });

            modelBuilder.Entity("api.Model.DoctorWorking", b =>
                {
                    b.HasOne("api.Model.DoctorProfile", null)
                        .WithMany()
                        .HasForeignKey("DoctorUuid")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("api.Model.TimeWorking", null)
                        .WithMany()
                        .HasForeignKey("WorkingUuid")
                        .OnDelete(DeleteBehavior.NoAction);
                });

            modelBuilder.Entity("api.Model.ExportTicket", b =>
                {
                    b.HasOne("api.Model.Account", null)
                        .WithMany()
                        .HasForeignKey("AccountUuid")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("api.Model.Hospital", null)
                        .WithMany()
                        .HasForeignKey("HospitalUuid")
                        .OnDelete(DeleteBehavior.NoAction);
                });

            modelBuilder.Entity("api.Model.ExportTicketDetail", b =>
                {
                    b.HasOne("api.Model.ExportTicket", null)
                        .WithMany()
                        .HasForeignKey("ExportTicketUuid")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("api.Model.Medicine", null)
                        .WithMany()
                        .HasForeignKey("MedicineUuid")
                        .OnDelete(DeleteBehavior.NoAction);
                });

            modelBuilder.Entity("api.Model.HospitalDepartment", b =>
                {
                    b.HasOne("api.Model.Department", null)
                        .WithMany()
                        .HasForeignKey("DepartmentUuid")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("api.Model.Hospital", null)
                        .WithMany()
                        .HasForeignKey("HospitalUuid")
                        .OnDelete(DeleteBehavior.NoAction);
                });

            modelBuilder.Entity("api.Model.HospitalMedicalService", b =>
                {
                    b.HasOne("api.Model.Hospital", null)
                        .WithMany()
                        .HasForeignKey("HospitalUuid")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("api.Model.MedicalService", null)
                        .WithMany()
                        .HasForeignKey("MedicalServiceUuid")
                        .OnDelete(DeleteBehavior.NoAction);
                });

            modelBuilder.Entity("api.Model.HospitalWorking", b =>
                {
                    b.HasOne("api.Model.Hospital", null)
                        .WithMany()
                        .HasForeignKey("HospitalUuid")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("api.Model.TimeWorking", null)
                        .WithMany()
                        .HasForeignKey("WorkingUuid")
                        .OnDelete(DeleteBehavior.NoAction);
                });

            modelBuilder.Entity("api.Model.ImportTicket", b =>
                {
                    b.HasOne("api.Model.Account", null)
                        .WithMany()
                        .HasForeignKey("AccountUuid")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("api.Model.Hospital", null)
                        .WithMany()
                        .HasForeignKey("HospitalUuid")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("api.Model.Provider", null)
                        .WithMany()
                        .HasForeignKey("ProviderUuid")
                        .OnDelete(DeleteBehavior.NoAction);
                });

            modelBuilder.Entity("api.Model.ImportTicketDetail", b =>
                {
                    b.HasOne("api.Model.ImportTicket", null)
                        .WithMany()
                        .HasForeignKey("ImportTicketUuid")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("api.Model.Medicine", null)
                        .WithMany()
                        .HasForeignKey("MedicineUuid")
                        .OnDelete(DeleteBehavior.NoAction);
                });

            modelBuilder.Entity("api.Model.MedicineInventory", b =>
                {
                    b.HasOne("api.Model.Hospital", null)
                        .WithMany()
                        .HasForeignKey("HospitalUuid")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("api.Model.Medicine", null)
                        .WithMany()
                        .HasForeignKey("MedicineUuid")
                        .OnDelete(DeleteBehavior.NoAction);
                });

            modelBuilder.Entity("api.Model.PatientProfile", b =>
                {
                    b.HasOne("api.Model.Account", null)
                        .WithOne()
                        .HasForeignKey("api.Model.PatientProfile", "AccountUuid")
                        .OnDelete(DeleteBehavior.NoAction);
                });

            modelBuilder.Entity("api.Model.Prescription", b =>
                {
                    b.HasOne("api.Model.Appointment", null)
                        .WithMany()
                        .HasForeignKey("AppointmentUuid")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("api.Model.DoctorProfile", null)
                        .WithMany()
                        .HasForeignKey("DoctorProfileUuid")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("api.Model.Hospital", null)
                        .WithMany()
                        .HasForeignKey("HospitalUuid")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("api.Model.PatientProfile", null)
                        .WithMany()
                        .HasForeignKey("PatientProfileUuid")
                        .OnDelete(DeleteBehavior.NoAction);
                });

            modelBuilder.Entity("api.Model.PrescriptionDetail", b =>
                {
                    b.HasOne("api.Model.Medicine", null)
                        .WithMany()
                        .HasForeignKey("MedicineUuid")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("api.Model.Prescription", null)
                        .WithMany()
                        .HasForeignKey("PrescriptionUuid")
                        .OnDelete(DeleteBehavior.NoAction);
                });

            modelBuilder.Entity("api.Model.ReviewDoctor", b =>
                {
                    b.HasOne("api.Model.DoctorProfile", null)
                        .WithMany()
                        .HasForeignKey("DoctorUuid")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("api.Model.PatientProfile", null)
                        .WithMany()
                        .HasForeignKey("PatientUuid")
                        .OnDelete(DeleteBehavior.NoAction);
                });

            modelBuilder.Entity("api.Model.ReviewHospital", b =>
                {
                    b.HasOne("api.Model.Hospital", null)
                        .WithMany()
                        .HasForeignKey("HospitalUuid")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("api.Model.PatientProfile", null)
                        .WithMany()
                        .HasForeignKey("PatientUuid")
                        .OnDelete(DeleteBehavior.NoAction);
                });

            modelBuilder.Entity("api.Model.ReviewMedicalService", b =>
                {
                    b.HasOne("api.Model.MedicalService", null)
                        .WithMany()
                        .HasForeignKey("MedicalServiceUuid")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("api.Model.PatientProfile", null)
                        .WithMany()
                        .HasForeignKey("PatientUuid")
                        .OnDelete(DeleteBehavior.NoAction);
                });

            modelBuilder.Entity("api.Model.RolePermission", b =>
                {
                    b.HasOne("api.Model.Permission", null)
                        .WithMany()
                        .HasForeignKey("PermissionUuid")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("api.Model.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleUuid")
                        .OnDelete(DeleteBehavior.NoAction);
                });

            modelBuilder.Entity("api.Model.Room", b =>
                {
                    b.HasOne("api.Model.Hospital", null)
                        .WithMany()
                        .HasForeignKey("HospitalUuid")
                        .OnDelete(DeleteBehavior.NoAction);
                });

            modelBuilder.Entity("api.Model.ServiceWorking", b =>
                {
                    b.HasOne("api.Model.MedicalService", null)
                        .WithMany()
                        .HasForeignKey("ServiceUuid")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("api.Model.TimeWorking", null)
                        .WithMany()
                        .HasForeignKey("WorkingUuid")
                        .OnDelete(DeleteBehavior.NoAction);
                });
#pragma warning restore 612, 618
        }
    }
}
